name: Go Package Release
on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  go-auto-ci:
    uses:  tommzn/github-ci/.github/workflows/go.pkg.auto-ci-with-coveralls.yml@v1.0.80
